version: "3.9"

services:

  client:
    container_name: "client"
    build:
      context: ./web
    ports:
      - ${CLIENT_EXTERNAL_PORT}:3000
    volumes:
      - ./web:/app
      - /app/node_modules


  server:
    container_name: "api"
    build:
      context: ./api    
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    volumes:
      - ./api:/server
    restart: unless-stopped
    depends_on:
      - selenium  

  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./web/build:/usr/share/nginx/html
    depends_on:
      - client
      - server

  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444    
