version: "3.9"

services:
  server:
    container_name: "api"
    build:
      context: ./api
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    volumes:
      - ./api:/server
    restart: unless-stopped
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
